name: CI Orchestration Template

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
    secrets:
      SONAR_TOKEN:
        required: true
      SONAR_HOST_URL:
        required: true
      SNYK_TOKEN:
        required: true
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  sonarqube:
    uses: QuickHaulTransits/quickhaul-templates/.github/workflows/_sonarqube.yml@main
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  snyk:
    needs: sonarqube
    uses: QuickHaulTransits/quickhaul-templates/.github/workflows/_snyk.yml@main
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  docker:
    needs: snyk
    if: github.event_name == 'push'
    uses: QuickHaulTransits/quickhaul-templates/.github/workflows/_docker-ci.yml@main
    with:
      image-name: quickhaul-${{ inputs.service-name }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  trivy:
    needs: docker
    if: github.event_name == 'push'
    uses: QuickHaulTransits/quickhaul-templates/.github/workflows/_trivy.yml@main
    with:
      image-name: quickhaul-${{ inputs.service-name }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
